### ISSUE TITLE
Fix set-output

### ISSUE THREAD

**Issue by abhiyerra** [opszero/actions-cloudflare-dns#3]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by thaunghtike-share** [comment]
There is no set-output when I use v3.1.0 .. https://github.com/thaunghtike-share/tho-amis/actions/runs/4631059363/jobs/8193455490

**Comment by thaunghtike-share** [comment]
`name: example
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: opszero/actions-cloudflare-dns@v3.1.0
        with:
          type: "A"
          name: "review.mytest.com"
          content: "8.8.8.8"
          ttl: 1
          proxied: true
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}`
